### ISSUE TITLE
🐛 [BUG] Error Fetching All Gists

### ISSUE THREAD

**Issue by chirag3003** [BRAVO68WEB/shx#90]
### Description

I experienced two issues at:-
- GET /gist -> Get All Gists Routes
- POST /gist -> Create a new gist

Can you check it and fix it?

### Reproduction URL

https://github.com/bravo68web/shx

### Reproduction steps

```bash
Postman Request to /gist API
```

### Logs

```bash
{
    "message": "OFFSET must not be negative: {\"response\":{\"errors\":[{\"message\":\"OFFSET must not be negative\",\"extensions\":{\"path\":\"$\",\"code\":\"data-exception\"}}],\"status\":200,\"headers\":{}},\"request\":{\"query\":\"\\n\\t\\t\\tquery listGists($searchString: String!, $pageNo: Int!, $pageSize: Int!) {\\n\\t\\t\\t\\tgists(\\n\\t\\t\\t\\t\\twhere: {\\n\\t\\t\\t\\t\\t\\t_or: [\\n\\t\\t\\t\\t\\t\\t\\t{ content: { _iregex: $searchString } }\\n\\t\\t\\t\\t\\t\\t\\t{ gist_url_key: { _iregex: $searchString } }\\n\\t\\t\\t\\t\\t\\t]\\n\\t\\t\\t\\t\\t}\\n\\t\\t\\t\\t\\tlimit: $pageSize\\n\\t\\t\\t\\t\\toffset: $pageNo\\n\\t\\t\\t\\t) {\\n\\t\\t\\t\\t\\tgistID\\n\\t\\t\\t\\t\\tcontent\\n\\t\\t\\t\\t\\tgist_url_key\\n\\t\\t\\t\\t\\tcreated_on\\n\\t\\t\\t\\t\\tisPrivate\\n\\t\\t\\t\\t\\tisOneTimeOnly\\n\\t\\t\\t\\t\\tviews\\n\\t\\t\\t\\t}\\n\\t\\t\\t}\\n\\t\\t\",\"variables\":{\"searchString\":\"\",\"pageNo\":-10,\"pageSize\":10}}}",
    "error": true,
    "data": null,
    "error_stack": "Error: OFFSET must not be negative: {\"response\":{\"errors\":[{\"message\":\"OFFSET must not be negative\",\"extensions\":{\"path\":\"$\",\"code\":\"data-exception\"}}],\"status\":200,\"headers\":{}},\"request\":{\"query\":\"\\n\\t\\t\\tquery listGists($searchString: String!, $pageNo: Int!, $pageSize: Int!) {\\n\\t\\t\\t\\tgists(\\n\\t\\t\\t\\t\\twhere: {\\n\\t\\t\\t\\t\\t\\t_or: [\\n\\t\\t\\t\\t\\t\\t\\t{ content: { _iregex: $searchString } }\\n\\t\\t\\t\\t\\t\\t\\t{ gist_url_key: { _iregex: $searchString } }\\n\\t\\t\\t\\t\\t\\t]\\n\\t\\t\\t\\t\\t}\\n\\t\\t\\t\\t\\tlimit: $pageSize\\n\\t\\t\\t\\t\\toffset: $pageNo\\n\\t\\t\\t\\t) {\\n\\t\\t\\t\\t\\tgistID\\n\\t\\t\\t\\t\\tcontent\\n\\t\\t\\t\\t\\tgist_url_key\\n\\t\\t\\t\\t\\tcreated_on\\n\\t\\t\\t\\t\\tisPrivate\\n\\t\\t\\t\\t\\tisOneTimeOnly\\n\\t\\t\\t\\t\\tviews\\n\\t\\t\\t\\t}\\n\\t\\t\\t}\\n\\t\\t\",\"variables\":{\"searchString\":\"\",\"pageNo\":-10,\"pageSize\":10}}}\n    at makeRequest (file:///home/chirag/Projects/shx/node_modules/graphql-request/src/index.ts:426:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async GistController.listGistsS (file:///home/chirag/Projects/shx/packages/api/services/gist.service.ts:160:7)\n    at async file:///home/chirag/Projects/shx/packages/api/controllers/gists.controller.ts:129:18"
}



{
    "statusCode": 400,
    "data": {
        "_original": {
            "content": "Raw Data from nothing",
            "isOneTimeOnly": false,
            "isPrivate": false
        },
        "details": [
            {
                "message": "\"isPrivate\" is not allowed",
                "path": [
                    "isPrivate"
                ],
                "type": "object.unknown",
                "context": {
                    "child": "isPrivate",
                    "label": "isPrivate",
                    "value": false,
                    "key": "isPrivate"
                }
            }
        ]
    }
}
```

### Browsers

Firefox, Chrome, Safari, Microsoft Edge, Opera

### OS

Windows, Linux, Mac

**Comment by BRAVO68WEB** [comment]
Fixing ASAP
